matrix:
  DEFAULT_ENVIRONMENT:
    - cdp-dev
    # - cdp-sys
  SLACK_NOTICE_CHANNEL_SUCCESS:
    - cdp-deploy-success
  SLACK_NOTICE_CHANNEL_FAILURE:
    - cdp-deploy-failure
  SLACK_NOTICE_ICON:
    - https://avatars.slack-edge.com/2019-03-25/588775175286_f3831480e0ca04ab5358_48.png
  SLACK_NOTICE_USERNAME:
    - Drone

pipeline:
  deploy:
    image: quay.io/ukhomeofficedigital/cdp-ci:latest
    secrets:
      - kube_server
      - kube_token
    commands:
      - sed -i 's?#!/bin/bash?#!/bin/bash -x?g' /usr/bin/run-operation.sh /usr/bin/deploy.sh /usr/bin/test.sh 
      - echo `pwd`
      - which deploy.sh
      - /usr/bin/deploy.sh `pwd` ${DEFAULT_ENVIRONMENT}
    when:
      event: [push, deployment]
      # branch: [master]

  perf_test:
    image: quay.io/ukhomeofficedigital/cdp-ci:latest
    secrets:
      - kube_server
      - kube_token
    commands:
      - echo `pwd`
      - which test.sh
      - /usr/bin/test.sh `pwd` ${DEFAULT_ENVIRONMENT}
    when:
      event: [push, deployment]
      # branch: [master]

  notify_slack_success_push:
    image: plugins/slack:1.2
    secrets:
      - source: "slack_webhook_cdp_deploy_success"
        target: slack_webhook
    channel: ${SLACK_NOTICE_CHANNEL_SUCCESS}
    username: ${SLACK_NOTICE_USERNAME}
    icon_url: ${SLACK_NOTICE_ICON}
    template: >
      *Deployed to ${DEFAULT_ENVIRONMENT} * - <{{build.link}}|#{{build.number}}>
    when:
      branch: [master]
      event: push
      status: success

  notify_slack_failure_push:
    image: plugins/slack:1.2
    secrets:
      - source: "slack_webhook_cdp_deploy_failure"
        target: slack_webhook
    channel: ${SLACK_NOTICE_CHANNEL_FAILURE}
    username: ${SLACK_NOTICE_USERNAME}
    icon_url: ${SLACK_NOTICE_ICON}
    template: >
      *Failed to deploy to ${DEFAULT_ENVIRONMENT}*

      Author: {{build.author}}

      Duration: {{since job.started}}
      Job: <{{build.link}}|#{{build.number}}>

      Commit: {{build.commit}}
    when:
      branch: [master]
      event: push
      status: failure
