apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  downscaler/uptime: Mon-Fri 08:00-19:00 Europe/London

resources:
  - cdp-deployment-templates/k8s-template/tinkerpop-graphdb-schema-loader.yaml
  - cdp-deployment-templates/k8s-template/elasticsearch.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: tinkerpop-graphdb-schema-loader
    files:
      - cdp-deployment-templates/conf-template/graphdb/persona/schema-loader/gremlin-server-embedded.yml
      - cdp-deployment-templates/conf-template/graphdb/persona/schema-loader/graph-schema.json
      - cdp-deployment-templates/conf-template/graphdb/common/janusgraph-embedded.properties
      - cdp-deployment-templates/conf-template/graphdb/common/embedded-backend.yaml
      - cdp-deployment-templates/conf-template/graphdb/common/graphdb-prometheus-jmx.yaml
  - name: envoy
    files:
      - cdp-deployment-templates/conf-template/envoy/envoy.yaml

# secretGenerator used to push AWS creds to k8s on the command line
# when running from Drone, assuming the secret has already been created
# secretGenerator:
#   - name: tinkerpop-graphdb
#     type: Opaque
#     env: awscreds.txt

